places_remember/impressions/urls.py
from django.urls import path
from impressions.views import ImpressionCreateView, ImpressionDetailView

app_name = 'impressions'
urlpatterns = [
    path('<int:pk>/', ImpressionDetailView.as_view(), name='impression-detail'),
    path('', ImpressionCreateView.as_view(), name='create'),
]

places_remember/places_remember/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from places_remember.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(), name='home'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('users/', include('users.urls'), name='users'),
    path('impressions/', include('impressions.urls'), name='impressions'),
    path('', RedirectView.as_view(url='/home')),
]

places_remember/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

app_name = 'users'
urlpatterns = [
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
]

places_remember/impressions/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.db.models import CharField
from django.urls import reverse
from users.models import CustomUser

from .validators import long_lat_validator

DEFAULT_POINT_COORDINATES = {
    # coordinates of Krasnoyarsk
    'x': 56.01416977236943,
    'y': 92.85782247644305,
}


class Impression(models.Model):
    """
    Impression about some location
    Attributes:
        title (CharField): Title of description
        description (TextField): Description of some location
        location (PointField): Coordinates of location
        user (CustomUser): User that create this impression
    """

    title = models.CharField(
        max_length=50,
        blank=False,
    )
    description = models.TextField(
        blank=True,
        default='',
    )
    location = models.PointField(
        default=Point(**DEFAULT_POINT_COORDINATES),
        validators=[long_lat_validator],
    )
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='impressions',
    )

    def __str__(self) -> CharField:
        return self.title

places_remember/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import TextField, URLField


class CustomUser(AbstractUser):
    """
    Impression about some location
    Attributes:
        avatar (URLField): url to profile pic
        backend_name (TextField): backend name through which the user auth
    """
    avatar = URLField(default='')
    backend_name = TextField(default='google-oauth2')

places_remember/impressions/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout, Submit
from django.forms import ModelForm
from impressions.models import Impression
from leaflet.forms.fields import PointField
from leaflet.forms.widgets import LeafletWidget

LEAFLET_WIDGET_ATTRS = {
    'map_height': '200%',
    'map_width': '200%',
    'map_srid': 4326,
}


class ImpressionCreationForm(ModelForm):
    """
    Form to create instance of Impression class
    """
    location = PointField(widget=LeafletWidget(attrs=LEAFLET_WIDGET_ATTRS))

    class Meta:
        model = Impression
        fields = (
            'title',
            'description',
            'location',
        )
        widgets = {'location': LeafletWidget()}

    helper = FormHelper()
    helper.form_class = 'form-group'
    helper.layout = Layout(
        Field('title', css_class='form-control mt-2 mb-3'),
        Field('description', rows="3", css_class='form-control mb-3'),
        Field('location', css_class='form-control w-0 mb-3'),
        Submit('submit', 'Submit'),
    )

places_remember/impressions/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from impressions.forms import ImpressionCreationForm
from impressions.models import Impression


class ImpressionDetailView(DetailView):
    """
    View with information about impression
    """
    template_name = 'impression.html'
    model = Impression

    def get_object(self, queryset=None) -> Impression:
        """Check that this impression was created by current user
        Returns:
            Impression class or raise Http404(Exception)
        """
        obj = super().get_object()
        if not obj.user == self.request.user:
            raise Http404
        return obj


class ImpressionCreateView(LoginRequiredMixin, CreateView):
    """
    View to create some impression
    """
    form_class = ImpressionCreationForm
    success_url = reverse_lazy('home')
    template_name = 'create_impression.html'

    def form_valid(self, form) -> HttpResponseRedirect:
        """
        Link impression with user
        Args:
            form: form with full information but user
        Returns:
            form with full information about place
        """
        form.instance.user = self.request.user
        return super().form_valid(form)

places_remember/places_remember/views.py
from django.views.generic import DetailView
from users.models import CustomUser


class HomeView(DetailView):
    """
    View where user can login, check all impressions or logout/disconnect
    """
    template_name = 'home.html'
    model = CustomUser

    def get_object(self, queryset=None):
        """
        Add current user to template to check inside it is user auth or not
        """
        return self.request.user

places_remember/users/views.py
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy


class CustomUserLogoutView(LogoutView):
    """
    View to logout
    """
    success_url = reverse_lazy('home')

places_remember/impressions/templates/create_impression.html
{# template to create impression #}
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Create{% endblock %}
{% block content %}
{% load leaflet_tags %}
{% leaflet_js plugins="forms" %}
{% leaflet_css plugins="forms" %}
{% crispy form %}
<a href="{% url 'home' %}"> Home </a>
{% endblock %}

places_remember/impressions/templates/impression.html
{# template to visualize impression #}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ impression.title }}</title>
    {% load leaflet_tags %}
    {% leaflet_js %}
    {% leaflet_css %}
</head>
<body>
<main>
    <header>
        {% if user.is_authenticated %}
        <div>
            <h2>Привет {{ user.last_name }} {{ user.first_name }}!</h2>
            <img src="{{ user.avatar }}">
        </div>
        {% endif %}
    </header>
    <div>
        Название: {{impression.title}}
        <p style="word-wrap: break-word ">
            Описание: <br>
            {% autoescape on %}
            {{impression.description | linebreaksbr}}
            {% endautoescape %}
        </p>
    </div>
    <div>
        <script>
            // Add point on map
            function map_init_basic(map, options) {
                const long = "{{impression.location.x}}";
                const alti = "{{impression.location.y}}";
                L.marker([alti, long]).addTo(map);
                console.log(alti)
            }
        </script>
        <style>
            .leaflet-container {
                width: 50%;
                height: 50%;
            }
        </style>
        {% leaflet_map "map" callback="window.map_init_basic" %}
    </div>
    <a href="{% url 'home' %}"> Home </a>
</main>
</body>
</html>

places_remember/templates/base.html
{# Base html template. Visualize profile pic if it has #}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Django Custom User Model{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'impression.css' %}">
</head>
<body>
<main>
    <header>
        {% if user.is_authenticated %}
        <div>
            <h2>Привет {{ user.last_name }} {{ user.first_name }}!</h2>
            <img src="{{ user.avatar }}">
        </div>
        {% endif %}
    </header>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

places_remember/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div>
    {% if user.is_authenticated %}
    {% for impression in user.impressions.all %}
    <li>
        <a href="{% url 'impressions:impression-detail' impression.pk %}">{{ impression.title }}</a>
    </li>
    {% empty %}
    <div class="center" style="text-align: center">У вас нет ни одного воспоминания</div>
    {% endfor %}
    <p><a href="{% url 'impressions:create' %}">Добавить воспоминание</a></p>
    <a href="{% url 'users:logout' %}"> Выйти </a> <br>  <br>
    <form action="{% url 'social:disconnect' user.backend_name %}" method="post">
        {% csrf_token %}
        <button class="btn btn-warning btn-xs">
            Выйти и забыть аккаунт
        </button>
    </form>
    {% else %}
    <h2>Welcome to Place Remember</h2>
    <p>Login or Create your account</p>
    <a href="{% url 'social:begin' 'vk-oauth2' %}">Войти с помощью VK</a>
    <a href="{% url 'social:begin' 'google-oauth2' %}">Войти с помощью Google</a>
    {% endif %}
</div>
{% endblock %}